### ISSUE TITLE
autoload of roms question

### ISSUE THREAD

**Issue by telanus** [libretro/blueMSX-libretro#48]
Hi

Just a quick question about autoloading roms based on different systems, IE to load a coleco rom you either need to hand edit the retroarch-core-options.cfg file, or load a rom, change the machine exit RA restart RA and then load a game. and you need to do it each time you want to play on different systems emulated by bluemsx.

won't it be simpler (and more user-friendly) if you load a rom.col (for coleco) or rom.sg (for SG-1000) that the core then chooses the right system automagically.

**Comment by Tatsuya79** [comment]
The problem is that you have different machines that can run the same roms.
I don't want to force a particular choice here.
Also some roms have a generic extension that is used for several machines too.

The best solution would be to have Core Option Overrides for playlists, that's a common problem for all the multi-machines emulators.

**Comment by Tatsuya79** [comment]
I didn't think of a way to make it completely optional before, but that should do it now:
https://github.com/libretro/blueMSX-libretro/pull/55

**Comment by meepingsnesroms** [comment]
Can this be closed?

**Comment by telanus** [comment]
thanx @Tatsuya79
